### ISSUE TITLE
Hover Effect isn't applied correctly if a node has previously been selected

### ISSUE THREAD

**Issue by domi2120** [ckotzbauer/simple-tree-component#381]
When a node is selected and the component is clicked to change the node, the hover effect will be stuck on the first node

**Comment by ckotzbauer** [comment]
@domi2120 Could you please answer the following questions?
- Which mode is used?
- Which other settings are applied to the tree?
- Which browser do you use?
- Are there any special steps to reproduce this issue?

If the bug is not reproducible clearly, could you create a small example showing the issue?
Please provide as much infos as possible.

**Comment by domi2120** [comment]
Im no longer able to reproduce the described behavior,,  sorry for the trouble.
